runtime: custom
env: flex
service: fiap-feedback-app

service_account: sa-deploy-feedback-app@fiap-adj8-feedback-platform.iam.gserviceaccount.com

beta_settings:
  cloud_sql_instances: fiap-adj8-feedback-platform:us-central1:feedback-db-instance

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
